name: Update Links

on:
  workflow_dispatch:
  schedule:
    - cron: "49 12 14 11 2"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}

    - name: Make script executable
      run: chmod +x main.sh

    - name: Run Bash script
      id: script-output
      run: |
        output=$(./main.sh "${{ secrets.BOT_TOKEN }}" "input3.json")
        echo "CRON=$output" >> $GITHUB_OUTPUT

    - name: Set cron schedule
      run: |
        sed -i '0,/cron: ".*"/s/cron: ".*"/cron: "${{ steps.script-output.outputs.CRON }}"/' .github/workflows/inputUpdate.yml

    - name: Commit inputFile
      uses: EndBug/add-and-commit@v9
      with:
        add: 'input3.json' 
        message: 'chore: update Link'
        push: true

    - name: Commit workflow
      uses: EndBug/add-and-commit@v9
      with:
        add: '.github/workflows/inputUpdate.yml' 
        message: 'chore: set new runtime'
        push: true
